### ISSUE TITLE
[App Request] Wireguard-UI

### ISSUE THREAD

**Issue by mojothemonkey2** [IceWhaleTech/CasaOS-AppStore#120]
### App Information

- Name: Wireguard-UI
- Short Description: WebUI for confirguring Wireguard
- Official Website: https://hub.docker.com/r/ngoduykhanh/wireguard-ui
- GitHub Repository: https://github.com/ngoduykhanh/wireguard-ui
- Docker Image: ngoduykhanh/wireguard-ui:latest

### Why do you want this app?

Helps users easily manage Wireguard config.
Does a very similar job the the helper script https://github.com/angristan/wireguard-install
But all through a nice WebUI.

Note: this is NOT running wireguard itself, it just manages the config (for both server and clients).
You would want to install wireguard directly on the host.
And there is suggestion how to create a service to watch & restart wireguard service on config changes.

### Additional information?

Working docker compose:
```
version: "3"
services:
  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: Wireguard-UI
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - WGUI_USERNAME=casaos
      - WGUI_PASSWORD=casaos
    volumes:
      - /DATA/AppData/WireguardUI:/app/db
      - /etc/wireguard:/etc/wireguard  #we modify the host config
```
Port is fixed to 5000.
It does work in briged mode, apart from the "Status" page, for connected peer info. As this needs host network + NET_ADMIN.

There is also an arm version of the image: `ngoduykhanh/wireguard-ui:latest-arm64`
(not sure if we can make this a selectable / automated option from CasaOS appstore).
