### ISSUE TITLE
[App Request] Firefly III

### ISSUE THREAD

**Issue by regassa22** [IceWhaleTech/CasaOS-AppStore#402]
### App Information

- Name: Firefly III
- Short Description: Personal finances manager
- Official Website: https://firefly-iii.org/
- GitHub Repository: https://github.com/firefly-iii/firefly-iii
- Docker Image: fireflyiii/core:latest

### Why do you want this app?

I don't think there is a more complete option than this application for managing personal finances. Another detail is that it is extremely difficult to install on CasaOS (I haven't managed it so far because I'm a newbie) and I can't find tutorials for either CasaOS or portainer, which help me when installing.

### Additional information?

yml file:
https://raw.githubusercontent.com/firefly-iii/docker/main/docker-compose.yml

.env:
https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.env.example

.db.env:
https://raw.githubusercontent.com/firefly-iii/docker/main/database.env

**Comment by jkano** [comment]
This is how I manage to install Firefly III in CasaOS using manual install:

1. Click on the + button and **Install a customized app**
2. Click on the import button (located on the top right, next to the X to close)
3. In the Docker Compose Window paste the following:
<details>
<summary>View file</summary>

#### firefly.yml
```
version: '3.3'

services:
  firefly:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly-core
    restart: always
    volumes:
      - firefly_upload:/var/www/html/storage/upload
    networks:
      - firefly
    ports:
      - 80:8080
    depends_on:
      - db
    labels:
      icon: https://winsomnia.net/assets/icons/Firefly-iii.jpg
    environment:
      - ALLOW_WEBHOOKS=false
      - APP_DEBUG=true
      - APP_ENV=local
      - APP_KEY=<YOUR_KEY>
      - APP_LOG_LEVEL=notice
      - APP_NAME=Firefly
      - APP_URL=<YOUR_APP_URL>
      - AUDIT_LOG_CHANNEL=
      - AUDIT_LOG_LEVEL=emergency
      - AUTHENTICATION_GUARD=web
      - AUTHENTICATION_GUARD_EMAIL=
      - AUTHENTICATION_GUARD_HEADER=REMOTE_USER
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - CACHE_PREFIX=firefly
      - COOKIE_DOMAIN=
      - COOKIE_PATH=/
      - COOKIE_SAMESITE=lax
      - COOKIE_SECURE=false
      - CUSTOM_LOGOUT_URL=
      - DB_CONNECTION=mysql
      - DB_DATABASE=firefly
      - DB_HOST=db
      - DB_PASSWORD=dbpassword
      - DB_PORT=3306
      - DB_SOCKET=
      - DB_USERNAME=firefly
      - DEFAULT_LANGUAGE=en_US
      - DEFAULT_LOCALE=equal
      - DEMO_PASSWORD=
      - DEMO_USERNAME=
      - DISABLE_CSP_HEADER=false
      - DISABLE_FRAME_HEADER=false
      - DKR_BUILD_LOCALE=false
      - DKR_CHECK_SQLITE=true
      - DKR_RUN_MIGRATION=true
      - DKR_RUN_PASSPORT_INSTALL=true
      - DKR_RUN_REPORT=true
      - DKR_RUN_UPGRADE=true
      - DKR_RUN_VERIFY=true
      - ENABLE_EXTERNAL_MAP=false
      - ENABLE_EXTERNAL_RATES=false
      - FIREFLY_III_LAYOUT=v1
      - IPINFO_TOKEN=
      - LOG_CHANNEL=stack
      - MAIL_ENCRYPTION=null
      - MAIL_FROM=changeme@example.com
      - MAIL_HOST=null
      - MAIL_MAILER=log
      - MAIL_PASSWORD=null
      - MAIL_PORT=2525
      - MAIL_SENDMAIL_COMMAND=
      - MAIL_USERNAME=null
      - MAILGUN_DOMAIN=
      - MAILGUN_ENDPOINT=api.mailgun.net
      - MAILGUN_SECRET=
      - MANDRILL_SECRET=
      - MAP_DEFAULT_LAT=51.983333
      - MAP_DEFAULT_LONG=5.916667
      - MAP_DEFAULT_ZOOM=6
      - MYSQL_SSL_CA=
      - MYSQL_SSL_CAPATH=/etc/ssl/certs/
      - MYSQL_SSL_CERT=
      - MYSQL_SSL_CIPHER=
      - MYSQL_SSL_KEY=
      - MYSQL_SSL_VERIFY_SERVER_CERT=true
      - MYSQL_USE_SSL=false
      - PAPERTRAIL_HOST=
      - PAPERTRAIL_PORT=
      - PASSPORT_PRIVATE_KEY=
      - PASSPORT_PUBLIC_KEY=
      - PGSQL_SCHEMA=public
      - PGSQL_SSL_CERT=null
      - PGSQL_SSL_CRL_FILE=null
      - PGSQL_SSL_KEY=null
      - PGSQL_SSL_MODE=prefer
      - PGSQL_SSL_ROOT_CERT=null
      - PUSHER_ID=
      - PUSHER_KEY=
      - PUSHER_SECRET=
      - QUEUE_DRIVER=sync
      - REDIS_CACHE_DB=1
      - REDIS_DB=0
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=
      - REDIS_PATH=
      - REDIS_PORT=6379
      - REDIS_SCHEME=tcp
      - REDIS_USERNAME=
      - SEND_ERROR_MESSAGE=true
      - SEND_REPORT_JOURNALS=true
      - SESSION_DRIVER=file
      - SITE_OWNER=<YOUR_EMAIL>
      - SPARKPOST_SECRET=
      - STATIC_CRON_TOKEN=<STATIC_CRON_TOKEN>
      - TRACKER_SITE_ID=
      - TRACKER_URL=
      - TRUSTED_PROXIES=**
      - TZ=<YOUR_TIMEZONE_HERE>
      - VALID_URL_PROTOCOLS=
  
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly-db
    restart: always
    networks:
      - firefly
    volumes:
      - firefly_db:/var/lib/mysql
    labels:
      icon: https://winsomnia.net/assets/icons/Firefly-iii.jpg
    environment:
      - MYSQL_DATABASE=firefly
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
    
  cron:
    image: alpine
    hostname: cron
    container_name: firefly-cron
    restart: always
    networks:
      - firefly
    labels:
      icon: https://winsomnia.net/assets/icons/Firefly-iii.jpg
    command: 
      - sh
      - -c
      - echo "0 3 * * * wget -qO- http://app:8080/api/v1/cron/<STATIC_CRON_TOKEN>" | crontab - && crond -f -L /dev/stdout

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly:
    name: firefly
    driver: bridge
```

</details>

4. You will see a warning about needing to configure other things, it's fine, click **Ok**
5. Now you will have the following window (DO NOT CLICK INSTALL YET)
<p align="center">
<img src="https://github.com/IceWhaleTech/CasaOS-AppStore/assets/6852063/74b2699c-0348-4966-ac9a-8871f0fcb20a" width="400">
</p>
6. First give the App a name on the **Title** field.
7. Now, add the **web UI** host and port (i.e. 192.168.1.32 : 80) 
8.
