### ISSUE TITLE
Add CUPS - Print Server Container to App Store

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS-AppStore#41]
Back in the original RPi Project days, creating a print server for Windows, Linux, and MacOS hosts was a pretty popular topic. Would be nice to see you honor this tradition win an App Store Container.

REF: 1. https://medium.com/swlh/setup-a-print-server-using-raspberry-pi-cups-part-1-c8f3d48af047
         2. https://medium.com/@anirudhgupta281998/setup-a-print-server-using-raspberry-pi-cups-part-2-2d6d48ccdc32
         3. https://medium.com/@anirudhgupta281998/setup-a-print-server-using-raspberry-pi-cups-part-3-aaced48e9b89

Thanks

**Comment by sund3RRR** [comment]
I have a working CUPS compose file without privileged and without doing anything on host machine.
Based on [this](https://hub.docker.com/r/olbat/cupsd) image with included printing drivers.

```yml
name: hungry_andres
services:
  cupsd:
    cpu_shares: 90
    command: []
    container_name: cupsd
    deploy:
      resources:
        limits:
          memory: 15920M
    devices:
      - /dev/bus/usb:/dev/bus/usb
    hostname: cupsd
    image: olbat/cupsd:latest
    ports:
      - target: 631
        published: "631"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: casaos.local
  icon: https://raw.githubusercontent.com/vinceliuice/WhiteSur-icon-theme/master/src/apps/scalable/printer.svg
  index: /
  is_uncontrolled: false
  port_map: "631"
  scheme: http
  store_app_id: hungry_andres
  title:
    custom: CUPS
```
