### ISSUE TITLE
[App Request] Wallabag

### ISSUE THREAD

**Issue by noticons** [IceWhaleTech/CasaOS-AppStore#48]
### App Information

- Name: Wallabag
- Short Description: It's like an open source and self-hosted Pocket. "You can use wallabag on your computer, thanks to our web application. But you can also take wallabag everywhere. For example, it's possible to save an article on your laptop at work, start to read it on your smartphone in the subway and finish reading it on your ereader in your bed."
- Official Website: https://wallabag.org/en
- GitHub Repository: https://github.com/wallabag/wallabag
- Docker Image: wallabag/wallabag

### Additional information?

https://hub.docker.com/r/wallabag/wallabag/

**Comment by Virgus** [comment]
Great idea, I'd love to see this one added to the Apps repo!

**Comment by Virgus** [comment]
@pjssilva I just made a new try on wallabag and got almost to the end.

This is my wallabag.yaml file for CasaOS (I'm testing it on a RPi4 with 8GB):
```
name: Wallabag
services:
  wallabag:
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://localhost
    image: opencsi/wallabag:latest
    ports:
      - target: 80
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/wallabag/data
        target: /var/www/wallabag/data
      - type: bind
        source: /DATA/AppData/wallabag/images
        target: /var/www/wallabag/web/assets/images
    x-casaos:
      envs:
        - container: SYMFONY__ENV__DOMAIN_NAME
          description:
            en_us: ""
      ports:
        - container: "80"
          description:
            en_us: ""
      volumes:
        - container: /var/www/wallabag/data
          description:
            en_us: ""
        - container: /var/www/wallabag/web/assets/images
          description:
            en_us: ""
    devices: []
    cap_add: []
    command: []
    network_mode: bridge
    privileged: false
    container_name: Wallabag
    deploy:
      resources:
        limits:
          memory: 8185184256
x-casaos:
  architectures:
    - arm64
  author: CasaOS User
  category: BookmarkManager
  description:
    en_us: ""
  developer: wallabag.org
  icon: https://raw.githubusercontent.com/wallabag/logo/refs/heads/master/_default/icon/png/sm/logo-icon-bg-white-sm.png
  index: /
  main: wallabag
  hostname: YOURHOSTNAME
  port_map: "8080"
  scheme: http
  store_app_id: wallabag
  tagline:
    en_us:
  thumbnail: ""
  tips:
    custom:
  title:
    custom: ""
    en_us: Wallabag

```
What happens is that I'm accessing wallabag but the UI is only text. I'm stuck to this step. Maybe someone has the missing information to complete/correct my yaml file ?

![Image](https://github.com/user-attachments/assets/01cbdfce-2cfb-48f5-869e-3b91a0265b97)
