### ISSUE TITLE
[App Request] SimpleTorrent

### ISSUE THREAD

**Issue by sund3RRR** [IceWhaleTech/CasaOS-AppStore#488]
### App Information

- Name: SimpleTorrent
- Short Description: ☁️ Simple Torrent: a self-hosted remote torrent client (rebranded from Cloud Torrent)
- Official Website: None
- GitHub Repository: [https://github.com/boypt/simple-torrent](https://github.com/boypt/simple-torrent)
- Docker Image: boypt/cloud-torrent:latest

### Why do you want this app?

It is a really good and simple torrent client.

### Additional information?

Working compose file:

```yaml
name: successful_kraisorn
services:
  main_app:
    cpu_shares: 90
    command: []
    container_name: simple-torrent
    deploy:
      resources:
        limits:
          memory: 7936M
    hostname: simple-torrent
    image: boypt/cloud-torrent:latest
    labels:
      icon: https://raw.githubusercontent.com/vinceliuice/WhiteSur-icon-theme/master/src/apps/scalable/icloud.svg
    ports:
      - target: 3000
        published: "8087"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/SimpleTorrent/torrents
        target: /torrents
      - type: bind
        source: /DATA/AppData/SimpleTorrent/config
        target: /config
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: casaos.local
  icon: https://raw.githubusercontent.com/vinceliuice/WhiteSur-icon-theme/master/src/apps/scalable/icloud.svg
  index: /
  is_uncontrolled: false
  port_map: "8087"
  scheme: http
  store_app_id: successful_kraisorn
  title:
    custom: SimpleTorrent
```
