### ISSUE TITLE
[App Request] InvoiceNinja 5

### ISSUE THREAD

**Issue by uSlackr** [IceWhaleTech/CasaOS-AppStore#589]
### App Information

- Name: InvoiceNinja
- Short Description: Open source invoice, expense and time mgmt (and much more) platform
- Official Website: https://invoiceninja.github.io/en/
- GitHub Repository: https://github.com/invoiceninja
- Docker Image: ghcr.io/invoiceninja/invoiceninja:5

### Why do you want this app?

As a smart tech consultant working to bring smart tech to breweries and other beverage and food  businesses, I need a solid platform for tracking expenses and billing customers.  My first attempt with this was on umbrel, but it is clear your platform is much more dynamic.

### Additional information?

The full stack requires nginx and mariadb.  And of course, I want to ocnfigure it behins swag for cert mgmt.
Here is a working compose file
```
services:
  app_proxy:
    environment:
      APP_HOST: invoice-ninja_nginx_1
      APP_PORT: 80
      PROXY_AUTH_ADD: false
      PROXY_AUTH_WHITELIST: /api/*
    container_name: invoice-ninja_app_proxy_1
  nginx:
    image: >-
      nginx:1.21-alpine@sha256:686aac2769fd6e7bab67663fd38750c135b72d993d0bb0a942ab02ef647fc9c3
    init: true
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ${APP_DATA_DIR}/data/public:/var/www/app/public:ro
    depends_on:
      - app
    container_name: invoice-ninja_nginx_1
  app:
    image: >-
      invoiceninja/invoiceninja:5.10.27@sha256:e5711a1fad103334692d5116ae0d4e62a384b08d7b52c1abb8c7ec33d526f699
    user: '1500:1500'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/www/app/public:rw,delegated
      - ${APP_DATA_DIR}/data/storage:/var/www/app/storage:rw,delegated
    environment:
      APP_URL: https://in.gmartin.org/
      APP_KEY: ${APP_KEY:-unset}
      APP_DEBUG: false
      REQUIRE_HTTPS: true
      TRUSTED_PROXIES: '*'
      DB_HOST: invoice-ninja_db_1
      DB_DATABASE: invoiceninja
      DB_USERNAME: invoiceninja
      DB_PASSWORD: moneyprintergobrrr
      IN_USER_EMAIL: null
      IN_PASSWORD: null
    depends_on:
      - db
    container_name: invoice-ninja_app_1
  db:
    image: >-
      mariadb:10.5.12@sha256:dfcba5641bdbfd7cbf5b07eeed707e6a3672f46823695a0d3aba2e49bbd9b1dd
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: invoiceninja
      MYSQL_USER: invoiceninja
      MYSQL_PASSWORD: moneyprintergobrrr
      MYSQL_DATABASE: invoiceninja
    container_name: invoice-ninja_db_1
```
