### ISSUE TITLE
[App Request] Firefly III

### ISSUE THREAD

**Issue by SeinopSys** [IceWhaleTech/CasaOS-AppStore#652]
### App Information

- Name: Firefly III
- Short Description: A free and open source personal finance manager
- Official Website: https://www.firefly-iii.org/
- GitHub Repository: https://github.com/firefly-iii/firefly-iii/
- Docker Image: fireflyiii/core:latest, fireflyiii/data-importer:latest

### Why do you want this app?

I would like to use a self-hosted budget-tracking solution that has support for multiple currencies. I tried the existing Actual Budget app, but unfortunately that one seems to be wholly currency-unaware, and this was the next best alternative I could fined.

### Additional information?

The data importer could be set up as a separate app, it's not required for the core functionality. Currently I got a minimal setup working using the exported config below:

```
name: yourprojectname
services:
  core:
    cpu_shares: 50
    command: []
    container_name: firefly-iii
    deploy:
      resources:
        limits:
          memory: 8052M
    environment:
      - APP_KEY=********************************
      - APP_URL=http://example.com
      - DB_CONNECTION=pgsql
      - DB_DATABASE=casaos
      - DB_HOST=192.168.*******
      - DB_PASSWORD=casaos
      - DB_PORT=5432
      - DB_USERNAME=casaos
    hostname: firefly-iii
    image: fireflyiii/core:latest
    labels:
      icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/refs/heads/main/public/images/logo.png
    ports:
      - target: 8080
        published: "5006"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /tmp/casaos-compose-app-898331003/[object Object]
        target: /var/www/html/storage/upload
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: example.com
  icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/refs/heads/main/public/images/logo.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: yourprojectname
  title:
    custom: Firefly III
    en_us: core
```

This does not have the data import and also appears to shut down at random for some reason so I figured I probably messed something up, and it would be nice to have proper support for this. This config does also require the PostgreSQL app to be installed in addition, so if it were to be packaged as a self-contained app, it might be a good idea to include a database in the compose file. Looks like it also supports sqlite, so maybe that's a possible option as well. The project is based on Laravel (PHP) so its databse config options can be adjused based on that.
