### ISSUE TITLE
[App Request] Omada Controller

### ISSUE THREAD

**Issue by OhEhmGeh** [IceWhaleTech/CasaOS-AppStore#84]
### App Information

- Name: Omada Controller
- Short Description: Docker image to run TP-Link Omada SDN Controller to control TP-Link Omada EAP Series Wireless Access Points
- Official Website: https://www.tp-link.com/us/business-networking/omada-sdn-controller/
- GitHub Repository: https://github.com/mbentley/docker-omada-controller
- Docker Image: docker pull mbentley/omada-controller

### Why do you want this app?

Docker image to run TP-Link Omada SDN Controller to control TP-Link Omada EAP Series Wireless Access Points its like the Unfi Controller from Ubiquiti.

**Comment by SuperJC710e** [comment]
FWIW, here's a sanitized export from my "custom install" that could be used for a starting point.

```yaml
name: omada-controller
services:
  omada-controller:
    cpu_shares: 90
    command: []
    container_name: omada-controller
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 64M
    environment:
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PGID=1000
      - PORT_ADOPT_V1=29812
      - PORT_APP_DISCOVERY=27001
      - PORT_DISCOVERY=29810
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_UPGRADE_V1=29813
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PUID=1000
      - SHOW_MONGODB_LOGS=false
      - SHOW_SERVER_LOGS=true
      # - SSL_CERT_NAME=tls.crt
      # - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    image: mbentley/omada-controller:5.9
    labels:
      icon: https://www.tp-link.com/res/images/icons/tag-omada.svg
    ports:
      - target: 8088
        published: "8088"
        protocol: tcp
      - target: 8043
        published: "8043"
        protocol: tcp
      - target: 8843
        published: "8843"
        protocol: tcp
      - target: 27001
        published: "27001"
        protocol: udp
      - target: 29810
        published: "29810"
        protocol: udp
      - target: 29811
        published: 29811-29816
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/omada-controller/data
        target: /opt/tplink/EAPController/data
      - type: bind
        source: /DATA/AppData/omada-controller/logs
        target: /opt/tplink/EAPController/logs
    devices: []
    cap_add: []
    network_mode: host
    privileged: false
x-casaos:
  author: self
  category: Network
  hostname: ""
  icon: https://www.tp-link.com/res/images/icons/tag-omada.svg
  index: /
  port_map: "8043"
  scheme: https
  store_app_id: omada-controller
  tips: {}
  title:
    custom: omada-controller
    en-us: omada-controller
```
